DRY

diff --git a/bin/omarchy-branch-set b/bin/omarchy-branch-set
--- a/bin/omarchy-branch-set
+++ b/bin/omarchy-branch-set
@@ -9,9 +9,9 @@ else
   branch="$1"
 fi
 
-case "$branch" in
-  "master") git -C $OMARCHY_PATH switch master ;;
-  "rc") git -C $OMARCHY_PATH switch rc ;;
-  "dev") git -C $OMARCHY_PATH switch dev ;;
-  *) echo "Unknown branch: $branch"; exit 1; ;;
-esac
+if [[ "$branch" != "master" && "$branch" != "rc" && "$branch" != "edge" ]]; then
+  echo "Error: Invalid branch '$branch'. Must be one of: master, rc, edge"
+  exit 1
+fi
+
+git -C $OMARCHY_PATH switch $branch
